name: Generation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        run: ./generate.sh > filterlist.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Filterlists
          files: filterlist.txt
          tag_name: continuous
          prerelease: true
